version: '3.8'
services:
    postgres:
        image: postgres:14.5
        ports:
            - '5432:5432'
        restart: always
        volumes:
            - db_data:/var/lib/postgresql/data
        environment:
            POSTGRES_PASSWORD: 'password'
            POSTGRES_HOST_AUTH_METHOD: trust
volumes:
    db_data:
